language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ankancode/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ankancode/docker-react npm run test 
